SELECT *
FROM PARKINGUSER
FETCH FIRST 100 ROWS ONLY;

SELECT *
FROM PARKING
FETCH FIRST 100 ROWS ONLY;

SELECT *
FROM PARKINGSPOT
FETCH FIRST 100 ROWS ONLY;

SELECT *
FROM PAYMENT
FETCH FIRST 100 ROWS ONLY;

SELECT *
FROM STRIPECHARGE
FETCH FIRST 100 ROWS ONLY;

SELECT *
FROM CLIENTCAR
FETCH FIRST 100 ROWS ONLY;

SELECT *
FROM RESERVATION
FETCH FIRST 100 ROWS ONLY;

SELECT count(1) as reservations from RESERVATION;
SELECT count(1) as parkings from PARKING;
SELECT count(1) as parkingspots from PARKINGSPOT;
SELECT count(1) as parkingusers from PARKINGUSER;
SELECT count(1) as payments from PAYMENT;
SELECT count(1) as stripecharges from STRIPECHARGE;
SELECT count(1) as clientcars from CLIENTCAR;
